### PR TITLE
Fix/flatten inner errors

### PR DESCRIPTION
**Pull request by Andarist**
The first commit ports change from https://github.com/staltz/callbag-flatten/pull/15/files
and the second ports change from https://github.com/staltz/callbag-flatten/pull/16/files

### CODE REVIEW

**Comment by staltz** [comment]
@jvanbruegge I wonder what happened with the CI tests? Maybe it wants the branch to be `main`?

**Comment by jvanbruegge** [comment]
I don't know, it should run on all branches and only ignore markdown only changes

**Comment by staltz** [comment]
@jvanbruegge This was it: https://github.com/cyclejs/callbags/commit/f3cba6fba937b08f15df3f729802923c49223f56

**Comment by jvanbruegge** [comment]
Interesting, did not know that

**Review by staltz — APPROVED** [review]

**Pull request merged**
