### PR TITLE
Add new create operator

### PR DESCRIPTION
**Pull request by jvanbruegge**
This is similar to `xs.create`. I also used it to re-implement many of the provided factories in terms of `create`.

### CODE REVIEW

**Comment by jvanbruegge** [comment]
The nice thing about `create` is that it takes care of all the early termination logic

**Comment by jvanbruegge** [comment]
I added a callback to the create function, so now it is more a dual of `xs.create` with its `start` and `stop` methods

**Comment by staltz** [comment]
Neat! I never realized there could be a `create()` factory for callbags, but now in hindsight that's an obvious addition.

One comment, though, is that the best implementation for this would be a preprocessor macro, if JS (TS) had such, because currently this adds a bit on the call stack. It's not a big deal, and it won't be a performance bottleneck, but I would prefer that this library be as low level as possible. Note that in practice, Cycle.js users should/can use the wider ecosystem of Callbags. 

On the other hand, I begin to feel that it would be useful to have a TypeScript-built set of Callbags meant for Cycle.js. So it seems that we have two needs:

- A set of Callbags optimized for Cycle.js internals
- A set of Callbags meant for Cycle.js usage in apps

And `create()` seems like it fits the latter better. Even if we don't do this now (I am actually okay in merging this PR), I think eventually we should do those two. For instance, maybe we could even have a subdirectory in this repo of those optimized Callbags. What do you think?

**Comment by jvanbruegge** [comment]
You are right with the performance, the operators in this library should be as fast as they can reasonably be. I have reverted all the changes made to other operators and I also implemented `empty` and `never` as standalone callbags.
We will still need `create` because I am using it in a bunch of tests and I will most likely use it for some parts of the DOM driver

**Comment by staltz** [comment]
LGTM!

**Pull request merged**
