### PR TITLE
Add cleanup operator

### PR DESCRIPTION
**Pull request by jvanbruegge**
Missing tests for now

### CODE REVIEW

**Comment by staltz** [comment]
Interesting, you found a use case for this in the HTTP driver?

**Comment by staltz** [comment]
And inspired by https://github.com/cyclejs/cyclejs/pull/906, could the naming be `uponEnd`? (because it might be that there are use cases for this operator that are not strictly related to *cleanup*) How about also adding `uponStart`?

**Comment by jvanbruegge** [comment]
Yes, this I use this for easy aborting of in-flight requests. `minireq` gives you a function back that will cancel your request if it is called. So all I had to make aborting of requests work was;
```
const { promise, abort } = request(options);
pipe(
   fromPromise(promise),
   addCleanup(abort)
);
```

**Comment by jvanbruegge** [comment]
I am now adding tests, when this is merged I would release a new version of cycle/callbags

**Comment by jvanbruegge** [comment]
I now did:
- Renamed operator to `uponEnd`
- Added `uponStart`
- Added tests for both

**Comment by staltz** [comment]
PS: the implementation of uponStart / uponEnd looked elegant and symmetric :)

**Pull request merged**
